### ISSUE TITLE
Bios needed for missing webinars

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/cms#4]
Bios are needed for the following webinars:
- [x] Web Design is Hard
- [x] Right-Sizing Your Rapid Prototypes (Erin Young, Tracy Singleton)
- [x] Designing for Understanding (Stephanie Hay, John Hodgins)
- [x] Designing for Real People (~Eric Meyer~, Jim Webb)

**Add final copy for bios as comments to this issue**

Reference: https://github.com/gymnasium/cms/blob/master/todo.md

**Comment by jgagne** [comment]
# Right-Sizing Your Rapid Prototypes

## Erin Young

Erin Young is Founder and Principal Consultant of Slide UX, an Austin-based business that help product and marketing teams design useful, easy-to-use, and optimized user experiences.

## Tracy Singleton

Tracy Singleton is a former client of Slide UX and currently Group Manager of Customer Success at Aha!, a software firm based in Austin, TX.

Preview: https://gymnasium.github.io/cms/webinars/right-sizing-your-rapid-prototypes/

**Comment by jgagne** [comment]
# Designing for Understanding

## Stephanie Hay

Stephanie Hay is VP Design of Integrated Experiences at Capital One. She co-founded FastCustomer, and was co-founding editor of WorkDesign.com and has designed content for UIE, Ben & Jerry’s, and the Annie E. Casey Foundation.

## John Hodgins

John Hodgins is Senior Communications Manager at The Annie E. Casey Foundation, a philanthropic organization devoted to improving the well-being of American children.

Preview: https://gymnasium.github.io/cms/webinars/designing-for-understanding/

**Comment by jgagne** [comment]
# Designing for Real People

## Eric Meyer

Eric A. Meyer is an author, speaker, blogger, sometime teacher and consultant, technical lead at Rebecca’s Gift, and co-founder of An Event Apart. He’s been working on the Web since 1993 and still finds it deeply compelling.

## Jim Webb

Jim Webb is a web developer and teacher based in Washington, D.C., with more than 1,800 hours of classroom experience teaching HTML, CSS, JavaScript, jQuery, PHP/MySQL, and WordPress.

Preview: https://gymnasium.github.io/cms/webinars/designing-for-real-people/
